insert into public.lessons (id, title, category, difficulty, lesson_goal, explanation_ko, estimated_minutes, key_expressions, mini_dialogue, practice_prompts)
values
  ('self-intro-name', 'Introduce Yourself Simply', 'self introduction', 'complete-beginner', 'Say your name and country politely.', '처음 만났을 때 가장 기본이 되는 자기소개를 연습합니다.', 4, '[{"japanese":"はじめまして"},{"japanese":"韓国から来ました"},{"japanese":"よろしくお願いします"}]', '[{"speaker":"staff","japanese":"はじめまして。お名前は？"},{"speaker":"learner","japanese":"はじめまして。ミナです。韓国から来ました。よろしくお願いします。"}]', '[{"id":"p1","instructionKo":"이름과 출신지를 포함해 짧게 인사해 보세요.","targetAnswer":"はじめまして。ミナです。韓国から来ました。よろしくお願いします。"}]'),
  ('self-intro-job', 'Talk About Your Job', 'self introduction', 'beginner', 'Say your job in one short sentence.', '직업과 근무지를 소개합니다.', 4, '[{"japanese":"会社員です"},{"japanese":"ソウルで働いています"}]', '[{"speaker":"staff","japanese":"お仕事は何ですか。"}]', '[{"id":"p1","instructionKo":"회사원이라고 말해 보세요.","targetAnswer":"会社員です。"}]'),
  ('cafe-order', 'Order Coffee', 'cafe', 'complete-beginner', 'Order one drink politely.', '카페 주문 기본형입니다.', 4, '[{"japanese":"アイスコーヒーをお願いします"},{"japanese":"店内で"}]', '[{"speaker":"staff","japanese":"ご注文は？"}]', '[{"id":"p1","instructionKo":"아이스커피 한 잔을 주문해 보세요.","targetAnswer":"アイスコーヒーをお願いします。"}]'),
  ('cafe-custom', 'Ask for Less Ice', 'cafe', 'beginner', 'Ask for one customization.', '옵션을 정중하게 요청합니다.', 4, '[{"japanese":"氷は少なめでお願いします"}]', '[{"speaker":"staff","japanese":"カスタムはありますか。"}]', '[{"id":"p1","instructionKo":"얼음을 적게 해 달라고 말해 보세요.","targetAnswer":"氷は少なめでお願いします。"}]'),
  ('convenience-pay', 'Pay at the Convenience Store', 'convenience store', 'complete-beginner', 'Answer simple cashier questions.', '편의점 계산 표현입니다.', 4, '[{"japanese":"袋は大丈夫です"},{"japanese":"カードで払います"}]', '[{"speaker":"staff","japanese":"袋はご利用ですか。"}]', '[{"id":"p1","instructionKo":"봉투는 괜찮다고 말해 보세요.","targetAnswer":"袋は大丈夫です。"}]'),
  ('convenience-ask', 'Ask Where Something Is', 'convenience store', 'beginner', 'Ask where an item is located.', '물건 위치를 묻습니다.', 4, '[{"japanese":"おにぎりはどこですか"}]', '[{"speaker":"learner","japanese":"おにぎりはどこですか。"}]', '[{"id":"p1","instructionKo":"삼각김밥이 어디 있는지 물어보세요.","targetAnswer":"おにぎりはどこですか。"}]'),
  ('restaurant-table', 'Ask for a Table', 'restaurant', 'complete-beginner', 'Say how many people are dining.', '식당 입장 표현입니다.', 4, '[{"japanese":"二人です"},{"japanese":"予約していません"}]', '[{"speaker":"staff","japanese":"何名様ですか。"}]', '[{"id":"p1","instructionKo":"두 명이라고 말해 보세요.","targetAnswer":"二人です。"}]'),
  ('restaurant-order', 'Order a Set Meal', 'restaurant', 'beginner', 'Order a meal and drink.', '메뉴를 선택해 주문합니다.', 5, '[{"japanese":"このセットをお願いします"},{"japanese":"飲み物はお茶で"}]', '[{"speaker":"learner","japanese":"このセットをお願いします。飲み物はお茶で。"}]', '[{"id":"p1","instructionKo":"이 세트를 달라고 말해 보세요.","targetAnswer":"このセットをお願いします。"}]'),
  ('directions-station', 'Ask for the Station', 'directions', 'complete-beginner', 'Ask how to get to the station.', '길을 묻는 기본 표현입니다.', 4, '[{"japanese":"駅はどちらですか"},{"japanese":"歩いて何分ですか"}]', '[{"speaker":"learner","japanese":"すみません。駅はどちらですか。"}]', '[{"id":"p1","instructionKo":"역이 어디인지 물어보세요.","targetAnswer":"すみません。駅はどちらですか。"}]'),
  ('directions-restroom', 'Ask for the Restroom', 'directions', 'beginner', 'Ask where the restroom is.', '화장실 위치를 묻습니다.', 4, '[{"japanese":"トイレはどこですか"}]', '[{"speaker":"learner","japanese":"トイレはどこですか。"}]', '[{"id":"p1","instructionKo":"화장실이 어디 있는지 물어보세요.","targetAnswer":"トイレはどこですか。"}]'),
  ('station-ticket', 'Buy a Ticket', 'train station', 'beginner', 'Ask how much a ticket costs.', '역 매표 표현입니다.', 4, '[{"japanese":"渋谷までいくらですか"},{"japanese":"切符を一枚ください"}]', '[{"speaker":"learner","japanese":"渋谷までいくらですか。"}]', '[{"id":"p1","instructionKo":"시부야까지 얼마인지 물어보세요.","targetAnswer":"渋谷までいくらですか。"}]'),
  ('station-transfer', 'Ask About Transfers', 'train station', 'lower-intermediate', 'Ask if you need to transfer.', '환승 여부를 묻습니다.', 5, '[{"japanese":"乗り換えは必要ですか"},{"japanese":"何番線ですか"}]', '[{"speaker":"learner","japanese":"乗り換えは必要ですか。"}]', '[{"id":"p1","instructionKo":"환승이 필요한지 물어보세요.","targetAnswer":"乗り換えは必要ですか。"}]'),
  ('shopping-size', 'Ask for a Different Size', 'shopping', 'beginner', 'Ask if another size is available.', '사이즈를 요청합니다.', 4, '[{"japanese":"Mサイズはありますか"},{"japanese":"試着してもいいですか"}]', '[{"speaker":"learner","japanese":"Mサイズはありますか。"}]', '[{"id":"p1","instructionKo":"M사이즈가 있는지 물어보세요.","targetAnswer":"Mサイズはありますか。"}]'),
  ('shopping-checkout', 'Pay for Clothes', 'shopping', 'complete-beginner', 'Ask to pay and request tax-free help.', '계산대 표현입니다.', 4, '[{"japanese":"これをお願いします"},{"japanese":"免税できますか"}]', '[{"speaker":"learner","japanese":"これをお願いします。免税できますか。"}]', '[{"id":"p1","instructionKo":"이걸로 하겠다고 말해 보세요.","targetAnswer":"これをお願いします。"}]'),
  ('hotel-checkin', 'Check In at a Hotel', 'hotel', 'beginner', 'Say you have a reservation.', '호텔 체크인 기본형입니다.', 5, '[{"japanese":"予約しています"},{"japanese":"朝食は何時からですか"}]', '[{"speaker":"learner","japanese":"予約しています。パクです。"}]', '[{"id":"p1","instructionKo":"예약했다고 말해 보세요.","targetAnswer":"予約しています。"}]'),
  ('hotel-help', 'Ask the Front Desk for Help', 'hotel', 'lower-intermediate', 'Request help from the front desk.', '추가 요청을 정중하게 말합니다.', 5, '[{"japanese":"タオルをもう一枚いただけますか"},{"japanese":"チェックアウトを少し延ばせますか"}]', '[{"speaker":"learner","japanese":"タオルをもう一枚いただけますか。"}]', '[{"id":"p1","instructionKo":"수건 한 장 더 요청해 보세요.","targetAnswer":"タオルをもう一枚いただけますか。"}]'),
  ('workplace-greeting', 'Greet a Coworker', 'workplace basics', 'complete-beginner', 'Use simple workplace greetings.', '회사 기본 인사입니다.', 4, '[{"japanese":"おはようございます"},{"japanese":"お疲れさまです"}]', '[{"speaker":"learner","japanese":"おはようございます。"}]', '[{"id":"p1","instructionKo":"출근해서 아침 인사를 해 보세요.","targetAnswer":"おはようございます。"}]'),
  ('workplace-meeting', 'Speak in a Simple Meeting', 'workplace basics', 'lower-intermediate', 'React briefly in a meeting.', '회의 반응 표현입니다.', 5, '[{"japanese":"わかりました"},{"japanese":"締め切りはいつですか"}]', '[{"speaker":"learner","japanese":"わかりました。締め切りはいつですか。"}]', '[{"id":"p1","instructionKo":"알겠다고 답해 보세요.","targetAnswer":"わかりました。"}]'),
  ('small-talk-weather', 'Talk About the Weather', 'daily small talk', 'complete-beginner', 'Make one weather comment.', '날씨 스몰톡입니다.', 4, '[{"japanese":"今日は寒いですね"},{"japanese":"雨が降りそうです"}]', '[{"speaker":"learner","japanese":"今日は寒いですね。"}]', '[{"id":"p1","instructionKo":"오늘 춥다고 말해 보세요.","targetAnswer":"今日は寒いですね。"}]'),
  ('small-talk-weekend', 'Talk About Weekend Plans', 'daily small talk', 'beginner', 'Say one weekend plan.', '주말 계획 스몰톡입니다.', 4, '[{"japanese":"週末は友だちに会います"},{"japanese":"あなたはどうですか"}]', '[{"speaker":"learner","japanese":"週末は友だちに会います。"}]', '[{"id":"p1","instructionKo":"주말에 친구를 만난다고 말해 보세요.","targetAnswer":"週末は友だちに会います。"}]'),
  ('daily-greeting-neighbor', 'Talk to a Neighbor', 'daily small talk', 'beginner', 'Greet a neighbor and make one comment.', '이웃과의 짧은 대화입니다.', 4, '[{"japanese":"こんにちは"},{"japanese":"今日はいい天気ですね"}]', '[{"speaker":"learner","japanese":"こんにちは。今日はいい天気ですね。"}]', '[{"id":"p1","instructionKo":"이웃에게 안녕하세요라고 말해 보세요.","targetAnswer":"こんにちは。"}]'),
  ('travel-airport', 'At the Airport Counter', 'travel', 'lower-intermediate', 'Ask about baggage and boarding time.', '공항 체크인 표현입니다.', 5, '[{"japanese":"荷物を預けたいです"},{"japanese":"搭乗は何時ですか"}]', '[{"speaker":"learner","japanese":"荷物を預けたいです。"}]', '[{"id":"p1","instructionKo":"짐을 부치고 싶다고 말해 보세요.","targetAnswer":"荷物を預けたいです。"}]'),
  ('jlpt-speaking-support', 'Explain Your Reason Briefly', 'JLPT support', 'lower-intermediate', 'Give a short reason using から.', '이유를 붙이는 연습입니다.', 5, '[{"japanese":"日本語が好きです"},{"japanese":"旅行で使いたいからです"}]', '[{"speaker":"learner","japanese":"旅行で使いたいからです。"}]', '[{"id":"p1","instructionKo":"여행에서 쓰고 싶어서라고 말해 보세요.","targetAnswer":"旅行で使いたいからです。"}]')
on conflict (id) do nothing;

insert into public.lesson_expressions (lesson_id, japanese, reading, meaning_ko, notes_ko, sort_order)
values
  ('self-intro-name', 'はじめまして', 'はじめまして', '처음 뵙겠습니다', '첫 인사', 1),
  ('cafe-order', 'アイスコーヒーをお願いします', 'あいすこーひーをおねがいします', '아이스커피 주세요', '카페 주문형', 1),
  ('restaurant-table', '二人です', 'ふたりです', '두 명입니다', '인원 표현', 1),
  ('hotel-checkin', '予約しています', 'よやくしています', '예약했습니다', '체크인 기본형', 1)
on conflict do nothing;

insert into public.lesson_dialogues (lesson_id, speaker, japanese, reading, meaning_ko, sort_order)
values
  ('self-intro-name', 'staff', 'はじめまして。お名前は？', 'はじめまして。おなまえは？', '처음 뵙겠습니다. 이름이 뭐예요?', 1),
  ('self-intro-name', 'learner', 'はじめまして。ミナです。韓国から来ました。よろしくお願いします。', 'はじめまして。みなです。かんこくからきました。よろしくおねがいします。', '처음 뵙겠습니다. 미나입니다. 한국에서 왔어요. 잘 부탁드립니다.', 2)
on conflict do nothing;
