import type { Lesson } from "@/lib/types";

export const demoLessons: Lesson[] = [
  {
    id: "self-intro-name",
    title: "Introduce Yourself Simply",
    category: "self introduction",
    difficulty: "complete-beginner",
    lessonGoal: "Say your name and where you are from politely.",
    explanationKo: "처음 만났을 때 가장 기본이 되는 자기소개 표현을 연습합니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "はじめまして", reading: "はじめまして", meaningKo: "처음 뵙겠습니다", notesKo: "첫 인사에 자주 씁니다." },
      { id: "e2", japanese: "韓国から来ました", reading: "かんこくからきました", meaningKo: "한국에서 왔어요", notesKo: "출신지 소개" },
      { id: "e3", japanese: "よろしくお願いします", reading: "よろしくおねがいします", meaningKo: "잘 부탁드립니다", notesKo: "마무리 인사" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "はじめまして。お名前は？", reading: "はじめまして。おなまえは？", meaningKo: "처음 뵙겠습니다. 이름이 뭐예요?" },
      { speaker: "learner", japanese: "はじめまして。ミナです。韓国から来ました。よろしくお願いします。", reading: "はじめまして。みなです。かんこくからきました。よろしくおねがいします。", meaningKo: "처음 뵙겠습니다. 미나입니다. 한국에서 왔어요. 잘 부탁드립니다." },
    ],
    prompts: [
      { id: "p1", situation: "처음 만나서 이름 말하기", instructionKo: "이름과 출신지를 포함해 짧게 인사해 보세요.", targetAnswer: "はじめまして。ミナです。韓国から来ました。よろしくお願いします。", targetReading: "はじめまして。みなです。かんこくからきました。よろしくおねがいします。", hints: ["はじめまして", "です", "韓国から来ました"], keyExpressionIds: ["e1", "e2", "e3"] },
      { id: "p2", situation: "좋아하는 공부 말하기", instructionKo: "일본어를 공부하고 있다고 덧붙여 보세요.", targetAnswer: "はじめまして。ミナです。韓国から来ました。日本語を勉強しています。よろしくお願いします。", targetReading: "はじめまして。みなです。かんこくからきました。にほんごをべんきょうしています。よろしくおねがいします。", hints: ["日本語を勉強しています"], keyExpressionIds: ["e1", "e2", "e3"] },
      { id: "p3", situation: "반갑다고 한마디 더하기", instructionKo: "만나서 반갑다고 덧붙여 보세요.", targetAnswer: "はじめまして。ミナです。お会いできてうれしいです。よろしくお願いします。", targetReading: "はじめまして。みなです。おあいできてうれしいです。よろしくおねがいします。", hints: ["お会いできてうれしいです"], keyExpressionIds: ["e1", "e3"] },
    ],
  },
  {
    id: "self-intro-job",
    title: "Talk About Your Job",
    category: "self introduction",
    difficulty: "beginner",
    lessonGoal: "Share your job or role in one short sentence.",
    explanationKo: "자기소개 다음 단계로 직업이나 역할을 자연스럽게 말합니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "会社員です", reading: "かいしゃいんです", meaningKo: "회사원입니다", notesKo: "직업 소개" },
      { id: "e2", japanese: "ソウルで働いています", reading: "ソウルではたらいています", meaningKo: "서울에서 일하고 있어요", notesKo: "근무지 소개" },
      { id: "e3", japanese: "よろしくお願いします", reading: "よろしくおねがいします", meaningKo: "잘 부탁드립니다", notesKo: "마무리 인사" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "お仕事は何ですか。", reading: "おしごとはなんですか。", meaningKo: "무슨 일을 하세요?" },
      { speaker: "learner", japanese: "会社員です。ソウルで働いています。", reading: "かいしゃいんです。ソウルではたらいています。", meaningKo: "회사원이에요. 서울에서 일하고 있어요." },
    ],
    prompts: [
      { id: "p1", situation: "직업 소개", instructionKo: "회사원이라고 말해 보세요.", targetAnswer: "会社員です。", targetReading: "かいしゃいんです。", hints: ["会社員です"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "근무지 포함", instructionKo: "서울에서 일한다고 덧붙여 보세요.", targetAnswer: "会社員です。ソウルで働いています。", targetReading: "かいしゃいんです。ソウルではたらいています。", hints: ["ソウルで働いています"], keyExpressionIds: ["e1", "e2"] },
      { id: "p3", situation: "정중하게 마무리", instructionKo: "짧은 자기소개를 정중하게 마무리해 보세요.", targetAnswer: "会社員です。ソウルで働いています。よろしくお願いします。", targetReading: "かいしゃいんです。ソウルではたらいています。よろしくおねがいします。", hints: ["よろしくお願いします"], keyExpressionIds: ["e1", "e2", "e3"] },
    ],
  },
  {
    id: "cafe-order",
    title: "Order Coffee",
    category: "cafe",
    difficulty: "complete-beginner",
    lessonGoal: "Order one drink politely.",
    explanationKo: "카페에서 가장 자주 쓰는 주문 패턴을 익힙니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "アイスコーヒーをお願いします", reading: "アイスコーヒーをおねがいします", meaningKo: "아이스커피 주세요", notesKo: "주문 기본형" },
      { id: "e2", japanese: "ひとつください", reading: "ひとつください", meaningKo: "하나 주세요", notesKo: "수량 표현" },
      { id: "e3", japanese: "店内で", reading: "てんないで", meaningKo: "매장에서요", notesKo: "먹고 갈 때" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "ご注文は？", reading: "ごちゅうもんは？", meaningKo: "주문하시겠어요?" },
      { speaker: "learner", japanese: "アイスコーヒーをお願いします。店内で。", reading: "アイスコーヒーをおねがいします。てんないで。", meaningKo: "아이스커피 주세요. 매장에서요." },
    ],
    prompts: [
      { id: "p1", situation: "음료 주문", instructionKo: "아이스커피 한 잔을 주문해 보세요.", targetAnswer: "アイスコーヒーをお願いします。", targetReading: "アイスコーヒーをおねがいします。", hints: ["アイスコーヒー", "お願いします"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "수량 말하기", instructionKo: "하나 달라고 말해 보세요.", targetAnswer: "アイスコーヒーをひとつください。", targetReading: "アイスコーヒーをひとつください。", hints: ["ひとつください"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "매장 이용", instructionKo: "매장에서 마신다고 덧붙여 보세요.", targetAnswer: "アイスコーヒーをお願いします。店内で。", targetReading: "アイスコーヒーをおねがいします。てんないで。", hints: ["店内で"], keyExpressionIds: ["e1", "e3"] },
    ],
  },
  {
    id: "cafe-custom",
    title: "Ask for Less Ice",
    category: "cafe",
    difficulty: "beginner",
    lessonGoal: "Make one simple customization request.",
    explanationKo: "주문 후 옵션을 정중하게 요청하는 연습입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "氷は少なめでお願いします", reading: "こおりはすくなめでおねがいします", meaningKo: "얼음은 적게 부탁해요", notesKo: "옵션 요청" },
      { id: "e2", japanese: "甘さは普通で", reading: "あまさはふつうで", meaningKo: "당도는 보통으로", notesKo: "옵션 조절" },
      { id: "e3", japanese: "できますか", reading: "できますか", meaningKo: "가능할까요?", notesKo: "가능 여부 질문" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "カスタムはありますか。", reading: "かすたむはありますか。", meaningKo: "옵션 변경 있으세요?" },
      { speaker: "learner", japanese: "氷は少なめでお願いします。", reading: "こおりはすくなめでおねがいします。", meaningKo: "얼음은 적게 부탁해요." },
    ],
    prompts: [
      { id: "p1", situation: "얼음 적게 요청", instructionKo: "얼음을 적게 해 달라고 말해 보세요.", targetAnswer: "氷は少なめでお願いします。", targetReading: "こおりはすくなめでおねがいします。", hints: ["少なめ"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "가능 여부 묻기", instructionKo: "얼음을 적게 할 수 있는지 물어보세요.", targetAnswer: "氷は少なめにできますか。", targetReading: "こおりはすくなめにできますか。", hints: ["できますか"], keyExpressionIds: ["e3"] },
      { id: "p3", situation: "당도는 보통", instructionKo: "당도는 보통이라고 덧붙여 보세요.", targetAnswer: "甘さは普通で、氷は少なめでお願いします。", targetReading: "あまさはふつうで、こおりはすくなめでおねがいします。", hints: ["甘さは普通で"], keyExpressionIds: ["e1", "e2"] },
    ],
  },
  {
    id: "convenience-pay",
    title: "Pay at the Convenience Store",
    category: "convenience store",
    difficulty: "complete-beginner",
    lessonGoal: "Answer simple cashier questions.",
    explanationKo: "편의점 계산대에서 자주 듣는 질문과 답을 익힙니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "袋は大丈夫です", reading: "ふくろはだいじょうぶです", meaningKo: "봉투는 괜찮아요", notesKo: "거절 표현" },
      { id: "e2", japanese: "カードで払います", reading: "カードではらいます", meaningKo: "카드로 계산할게요", notesKo: "결제 수단" },
      { id: "e3", japanese: "温めてください", reading: "あたためてください", meaningKo: "데워 주세요", notesKo: "음식 요청" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "袋はご利用ですか。", reading: "ふくろはごりようですか。", meaningKo: "봉투 필요하세요?" },
      { speaker: "learner", japanese: "袋は大丈夫です。カードで払います。", reading: "ふくろはだいじょうぶです。カードではらいます。", meaningKo: "봉투는 괜찮아요. 카드로 계산할게요." },
    ],
    prompts: [
      { id: "p1", situation: "봉투 거절", instructionKo: "봉투는 괜찮다고 말해 보세요.", targetAnswer: "袋は大丈夫です。", targetReading: "ふくろはだいじょうぶです。", hints: ["袋は大丈夫です"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "카드 결제", instructionKo: "카드로 계산한다고 말해 보세요.", targetAnswer: "カードで払います。", targetReading: "カードではらいます。", hints: ["カードで"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "도시락 데우기", instructionKo: "도시락을 데워 달라고 말해 보세요.", targetAnswer: "これを温めてください。", targetReading: "これをあたためてください。", hints: ["温めてください"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "convenience-ask",
    title: "Ask Where Something Is",
    category: "convenience store",
    difficulty: "beginner",
    lessonGoal: "Ask where an item is located.",
    explanationKo: "물건 위치를 묻는 기본 패턴을 연습합니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "おにぎりはどこですか", reading: "おにぎりはどこですか", meaningKo: "삼각김밥은 어디에 있나요?", notesKo: "위치 질문" },
      { id: "e2", japanese: "この近くにありますか", reading: "このちかくにありますか", meaningKo: "이 근처에 있나요?", notesKo: "근처 질문" },
      { id: "e3", japanese: "ありがとうございます", reading: "ありがとうございます", meaningKo: "감사합니다", notesKo: "응답 마무리" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "おにぎりはどこですか。", reading: "おにぎりはどこですか。", meaningKo: "삼각김밥은 어디에 있나요?" },
      { speaker: "staff", japanese: "あちらです。", reading: "あちらです。", meaningKo: "저쪽입니다." },
    ],
    prompts: [
      { id: "p1", situation: "상품 위치 묻기", instructionKo: "삼각김밥이 어디 있는지 물어보세요.", targetAnswer: "おにぎりはどこですか。", targetReading: "おにぎりはどこですか。", hints: ["どこですか"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "근처인지 확인", instructionKo: "이 근처에 있는지 물어보세요.", targetAnswer: "この近くにありますか。", targetReading: "このちかくにありますか。", hints: ["この近くにありますか"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "감사 인사", instructionKo: "안내를 듣고 감사하다고 말해 보세요.", targetAnswer: "ありがとうございます。", targetReading: "ありがとうございます。", hints: ["ありがとうございます"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "restaurant-table",
    title: "Ask for a Table",
    category: "restaurant",
    difficulty: "complete-beginner",
    lessonGoal: "Say how many people are dining.",
    explanationKo: "식당 입장 시 필요한 인원 표현을 익힙니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "二人です", reading: "ふたりです", meaningKo: "두 명입니다", notesKo: "인원 수" },
      { id: "e2", japanese: "予約していません", reading: "よやくしていません", meaningKo: "예약하지 않았어요", notesKo: "예약 여부" },
      { id: "e3", japanese: "禁煙席をお願いします", reading: "きんえんせきをおねがいします", meaningKo: "금연석 부탁합니다", notesKo: "좌석 요청" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "何名様ですか。", reading: "なんめいさまですか。", meaningKo: "몇 분이세요?" },
      { speaker: "learner", japanese: "二人です。予約していません。", reading: "ふたりです。よやくしていません。", meaningKo: "두 명이에요. 예약하지 않았어요." },
    ],
    prompts: [
      { id: "p1", situation: "인원 말하기", instructionKo: "두 명이라고 말해 보세요.", targetAnswer: "二人です。", targetReading: "ふたりです。", hints: ["二人です"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "예약 안 함", instructionKo: "예약하지 않았다고 말해 보세요.", targetAnswer: "予約していません。", targetReading: "よやくしていません。", hints: ["予約していません"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "금연석 요청", instructionKo: "금연석을 부탁해 보세요.", targetAnswer: "禁煙席をお願いします。", targetReading: "きんえんせきをおねがいします。", hints: ["禁煙席"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "restaurant-order",
    title: "Order a Set Meal",
    category: "restaurant",
    difficulty: "beginner",
    lessonGoal: "Order a dish and drink politely.",
    explanationKo: "식당에서 메뉴를 선택해 자연스럽게 주문합니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "このセットをお願いします", reading: "このせっとをおねがいします", meaningKo: "이 세트를 주세요", notesKo: "기본 주문" },
      { id: "e2", japanese: "飲み物はお茶で", reading: "のみものはおちゃで", meaningKo: "음료는 차로 할게요", notesKo: "선택지 답변" },
      { id: "e3", japanese: "おすすめは何ですか", reading: "おすすめはなんですか", meaningKo: "추천은 뭐예요?", notesKo: "추천 요청" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "このセットをお願いします。飲み物はお茶で。", reading: "このせっとをおねがいします。のみものはおちゃで。", meaningKo: "이 세트를 주세요. 음료는 차로 할게요." },
      { speaker: "staff", japanese: "かしこまりました。", reading: "かしこまりました。", meaningKo: "알겠습니다." },
    ],
    prompts: [
      { id: "p1", situation: "세트 주문", instructionKo: "이 세트를 달라고 말해 보세요.", targetAnswer: "このセットをお願いします。", targetReading: "このセットをおねがいします。", hints: ["このセット"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "음료 선택", instructionKo: "음료는 차로 하겠다고 말해 보세요.", targetAnswer: "飲み物はお茶でお願いします。", targetReading: "のみものはおちゃでおねがいします。", hints: ["お茶で"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "추천 묻기", instructionKo: "추천 메뉴를 물어보세요.", targetAnswer: "おすすめは何ですか。", targetReading: "おすすめはなんですか。", hints: ["おすすめ"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "directions-station",
    title: "Ask for the Station",
    category: "directions",
    difficulty: "complete-beginner",
    lessonGoal: "Ask how to get to the station.",
    explanationKo: "길을 물을 때 필요한 기본 표현입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "駅はどちらですか", reading: "えきはどちらですか", meaningKo: "역은 어디 쪽인가요?", notesKo: "정중한 방향 질문" },
      { id: "e2", japanese: "歩いて何分ですか", reading: "あるいてなんぷんですか", meaningKo: "걸어서 몇 분인가요?", notesKo: "소요 시간 질문" },
      { id: "e3", japanese: "まっすぐですか", reading: "まっすぐですか", meaningKo: "쭉 가면 되나요?", notesKo: "확인 질문" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "すみません。駅はどちらですか。", reading: "すみません。えきはどちらですか。", meaningKo: "실례합니다. 역은 어디 쪽인가요?" },
      { speaker: "staff", japanese: "あちらへまっすぐです。", reading: "あちらへまっすぐです。", meaningKo: "저쪽으로 쭉 가세요." },
    ],
    prompts: [
      { id: "p1", situation: "역 방향 묻기", instructionKo: "역이 어디인지 물어보세요.", targetAnswer: "すみません。駅はどちらですか。", targetReading: "すみません。えきはどちらですか。", hints: ["すみません", "どちらですか"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "도보 시간", instructionKo: "걸어서 몇 분인지 물어보세요.", targetAnswer: "歩いて何分ですか。", targetReading: "あるいてなんぷんですか。", hints: ["何分ですか"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "길 확인", instructionKo: "쭉 가면 되는지 확인해 보세요.", targetAnswer: "まっすぐですか。", targetReading: "まっすぐですか。", hints: ["まっすぐ"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "directions-restroom",
    title: "Ask for the Restroom",
    category: "directions",
    difficulty: "beginner",
    lessonGoal: "Politely ask where the restroom is.",
    explanationKo: "매장이나 역에서 화장실 위치를 물어보는 실전 표현입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "トイレはどこですか", reading: "といれはどこですか", meaningKo: "화장실은 어디에 있나요?", notesKo: "가장 기본" },
      { id: "e2", japanese: "この階にありますか", reading: "このかいにありますか", meaningKo: "이 층에 있나요?", notesKo: "층 질문" },
      { id: "e3", japanese: "ありがとうございます", reading: "ありがとうございます", meaningKo: "감사합니다", notesKo: "응답 마무리" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "トイレはどこですか。", reading: "といれはどこですか。", meaningKo: "화장실은 어디에 있나요?" },
      { speaker: "staff", japanese: "二階にあります。", reading: "にかいにあります。", meaningKo: "2층에 있어요." },
    ],
    prompts: [
      { id: "p1", situation: "화장실 위치 질문", instructionKo: "화장실이 어디 있는지 물어보세요.", targetAnswer: "トイレはどこですか。", targetReading: "トイレはどこですか。", hints: ["トイレ"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "층 확인", instructionKo: "이 층에 있는지 물어보세요.", targetAnswer: "この階にありますか。", targetReading: "このかいにありますか。", hints: ["この階"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "안내 후 감사", instructionKo: "안내를 듣고 감사하다고 말해 보세요.", targetAnswer: "ありがとうございます。", targetReading: "ありがとうございます。", hints: ["ありがとうございます"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "station-ticket",
    title: "Buy a Ticket",
    category: "train station",
    difficulty: "beginner",
    lessonGoal: "Ask how much a ticket costs.",
    explanationKo: "역 매표기 앞에서 바로 쓸 수 있는 질문입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "渋谷までいくらですか", reading: "しぶやまでいくらですか", meaningKo: "시부야까지 얼마예요?", notesKo: "요금 질문" },
      { id: "e2", japanese: "切符を一枚ください", reading: "きっぷをいちまいください", meaningKo: "표 한 장 주세요", notesKo: "표 구매" },
      { id: "e3", japanese: "この電車で大丈夫ですか", reading: "このでんしゃでだいじょうぶですか", meaningKo: "이 전철 타면 되나요?", notesKo: "탑승 확인" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "渋谷までいくらですか。", reading: "しぶやまでいくらですか。", meaningKo: "시부야까지 얼마예요?" },
      { speaker: "staff", japanese: "二百円です。", reading: "にひゃくえんです。", meaningKo: "200엔입니다." },
    ],
    prompts: [
      { id: "p1", situation: "요금 질문", instructionKo: "시부야까지 얼마인지 물어보세요.", targetAnswer: "渋谷までいくらですか。", targetReading: "しぶやまでいくらですか。", hints: ["までいくらですか"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "표 구매", instructionKo: "표 한 장 달라고 말해 보세요.", targetAnswer: "切符を一枚ください。", targetReading: "きっぷをいちまいください。", hints: ["一枚ください"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "전철 확인", instructionKo: "이 전철이 맞는지 확인해 보세요.", targetAnswer: "この電車で大丈夫ですか。", targetReading: "このでんしゃでだいじょうぶですか。", hints: ["大丈夫ですか"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "station-transfer",
    title: "Ask About Transfers",
    category: "train station",
    difficulty: "lower-intermediate",
    lessonGoal: "Ask if you need to transfer.",
    explanationKo: "환승 여부를 묻는 약간 더 긴 문장을 연습합니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "乗り換えは必要ですか", reading: "のりかえはひつようですか", meaningKo: "환승이 필요한가요?", notesKo: "환승 질문" },
      { id: "e2", japanese: "何番線ですか", reading: "なんばんせんですか", meaningKo: "몇 번 승강장이에요?", notesKo: "승강장 질문" },
      { id: "e3", japanese: "急行は止まりますか", reading: "きゅうこうはとまりますか", meaningKo: "급행이 서나요?", notesKo: "열차 종류 확인" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "新宿まで行きたいです。乗り換えは必要ですか。", reading: "しんじゅくまでいきたいです。のりかえはひつようですか。", meaningKo: "신주쿠까지 가고 싶어요. 환승이 필요한가요?" },
      { speaker: "staff", japanese: "一回必要です。", reading: "いっかいひつようです。", meaningKo: "한 번 필요해요." },
    ],
    prompts: [
      { id: "p1", situation: "환승 질문", instructionKo: "환승이 필요한지 물어보세요.", targetAnswer: "乗り換えは必要ですか。", targetReading: "のりかえはひつようですか。", hints: ["乗り換え"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "승강장 질문", instructionKo: "몇 번 승강장인지 물어보세요.", targetAnswer: "何番線ですか。", targetReading: "なんばんせんですか。", hints: ["何番線"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "급행 정차 여부", instructionKo: "급행이 서는지 물어보세요.", targetAnswer: "急行は止まりますか。", targetReading: "きゅうこうはとまりますか。", hints: ["急行"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "shopping-size",
    title: "Ask for a Different Size",
    category: "shopping",
    difficulty: "beginner",
    lessonGoal: "Ask if another size is available.",
    explanationKo: "옷가게에서 바로 쓸 수 있는 사이즈 질문입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "Mサイズはありますか", reading: "えむさいずはありますか", meaningKo: "M사이즈 있나요?", notesKo: "재고 질문" },
      { id: "e2", japanese: "試着してもいいですか", reading: "しちゃくしてもいいですか", meaningKo: "입어봐도 될까요?", notesKo: "시착 질문" },
      { id: "e3", japanese: "もう少し大きいサイズ", reading: "もうすこしおおきいさいず", meaningKo: "조금 더 큰 사이즈", notesKo: "비교 표현" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "Mサイズはありますか。", reading: "えむさいずはありますか。", meaningKo: "M사이즈 있나요?" },
      { speaker: "staff", japanese: "はい、あります。", reading: "はい、あります。", meaningKo: "네, 있어요." },
    ],
    prompts: [
      { id: "p1", situation: "사이즈 묻기", instructionKo: "M사이즈가 있는지 물어보세요.", targetAnswer: "Mサイズはありますか。", targetReading: "えむさいずはありますか。", hints: ["ありますか"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "시착 요청", instructionKo: "입어봐도 되는지 물어보세요.", targetAnswer: "試着してもいいですか。", targetReading: "しちゃくしてもいいですか。", hints: ["試着"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "더 큰 사이즈 요청", instructionKo: "조금 더 큰 사이즈가 있는지 물어보세요.", targetAnswer: "もう少し大きいサイズはありますか。", targetReading: "もうすこしおおきいサイズはありますか。", hints: ["もう少し大きい"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "shopping-checkout",
    title: "Pay for Clothes",
    category: "shopping",
    difficulty: "complete-beginner",
    lessonGoal: "Ask to pay and request tax-free help.",
    explanationKo: "계산대에서 짧게 필요한 말을 해봅니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "これをお願いします", reading: "これをおねがいします", meaningKo: "이걸로 할게요", notesKo: "구매 확정" },
      { id: "e2", japanese: "免税できますか", reading: "めんぜいできますか", meaningKo: "면세 되나요?", notesKo: "면세 질문" },
      { id: "e3", japanese: "レシートをください", reading: "レシートをください", meaningKo: "영수증 주세요", notesKo: "영수증 요청" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "これをお願いします。免税できますか。", reading: "これをおねがいします。めんぜいできますか。", meaningKo: "이걸로 할게요. 면세 되나요?" },
      { speaker: "staff", japanese: "パスポートをお願いします。", reading: "パスポートをおねがいします。", meaningKo: "여권 부탁드립니다." },
    ],
    prompts: [
      { id: "p1", situation: "구매 확정", instructionKo: "이걸로 하겠다고 말해 보세요.", targetAnswer: "これをお願いします。", targetReading: "これをおねがいします。", hints: ["これをお願いします"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "면세 질문", instructionKo: "면세 가능한지 물어보세요.", targetAnswer: "免税できますか。", targetReading: "めんぜいできますか。", hints: ["免税"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "영수증 요청", instructionKo: "영수증을 달라고 말해 보세요.", targetAnswer: "レシートをください。", targetReading: "レシートをください。", hints: ["レシート"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "hotel-checkin",
    title: "Check In at a Hotel",
    category: "hotel",
    difficulty: "beginner",
    lessonGoal: "Say you have a reservation and ask about breakfast.",
    explanationKo: "호텔 체크인 상황에서 가장 필요한 문장을 익힙니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "予約しています", reading: "よやくしています", meaningKo: "예약했습니다", notesKo: "체크인 기본" },
      { id: "e2", japanese: "パクです", reading: "ぱくです", meaningKo: "박입니다", notesKo: "성함 확인" },
      { id: "e3", japanese: "朝食は何時からですか", reading: "ちょうしょくはなんじからですか", meaningKo: "조식은 몇 시부터예요?", notesKo: "부가 정보 질문" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "予約しています。パクです。", reading: "よやくしています。ぱくです。", meaningKo: "예약했습니다. 박입니다." },
      { speaker: "staff", japanese: "確認いたします。", reading: "かくにんいたします。", meaningKo: "확인하겠습니다." },
    ],
    prompts: [
      { id: "p1", situation: "예약 있다고 말하기", instructionKo: "예약했다고 말해 보세요.", targetAnswer: "予約しています。", targetReading: "よやくしています。", hints: ["予約しています"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "이름 말하기", instructionKo: "박이라고 이름을 말해 보세요.", targetAnswer: "パクです。", targetReading: "ぱくです。", hints: ["です"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "조식 시간 질문", instructionKo: "조식이 몇 시부터인지 물어보세요.", targetAnswer: "朝食は何時からですか。", targetReading: "ちょうしょくはなんじからですか。", hints: ["何時からですか"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "hotel-help",
    title: "Ask the Front Desk for Help",
    category: "hotel",
    difficulty: "lower-intermediate",
    lessonGoal: "Request an extra towel or late checkout.",
    explanationKo: "프런트에 간단한 요청을 하는 실전 표현입니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "タオルをもう一枚いただけますか", reading: "たおるをもういちまいいただけますか", meaningKo: "수건 한 장 더 받을 수 있을까요?", notesKo: "정중 요청" },
      { id: "e2", japanese: "チェックアウトを少し延ばせますか", reading: "ちぇっくあうとをすこしのばせますか", meaningKo: "체크아웃을 조금 늦출 수 있을까요?", notesKo: "시간 요청" },
      { id: "e3", japanese: "部屋に持ってきてください", reading: "へやにもってきてください", meaningKo: "방으로 가져다 주세요", notesKo: "추가 요청" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "タオルをもう一枚いただけますか。", reading: "たおるをもういちまいいただけますか。", meaningKo: "수건 한 장 더 받을 수 있을까요?" },
      { speaker: "staff", japanese: "はい、承知しました。", reading: "はい、しょうちしました。", meaningKo: "네, 알겠습니다." },
    ],
    prompts: [
      { id: "p1", situation: "수건 추가 요청", instructionKo: "수건 한 장 더 요청해 보세요.", targetAnswer: "タオルをもう一枚いただけますか。", targetReading: "タオルをもういちまいいただけますか。", hints: ["もう一枚"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "체크아웃 연장", instructionKo: "체크아웃을 조금 늦출 수 있는지 물어보세요.", targetAnswer: "チェックアウトを少し延ばせますか。", targetReading: "チェックアウトをすこしのばせますか。", hints: ["少し延ばせますか"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "방으로 가져오기", instructionKo: "방으로 가져다 달라고 덧붙여 보세요.", targetAnswer: "部屋に持ってきてください。", targetReading: "へやにもってきてください。", hints: ["部屋に"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "workplace-greeting",
    title: "Greet a Coworker",
    category: "workplace basics",
    difficulty: "complete-beginner",
    lessonGoal: "Use simple workplace greetings.",
    explanationKo: "회사에서 자주 쓰는 짧은 인사 표현입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "おはようございます", reading: "おはようございます", meaningKo: "안녕하세요(아침)", notesKo: "아침 인사" },
      { id: "e2", japanese: "よろしくお願いします", reading: "よろしくおねがいします", meaningKo: "잘 부탁드립니다", notesKo: "첫 협업 인사" },
      { id: "e3", japanese: "お疲れさまです", reading: "おつかれさまです", meaningKo: "수고하십니다", notesKo: "업무 중 인사" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "おはようございます。今日もよろしくお願いします。", reading: "おはようございます。きょうもよろしくおねがいします。", meaningKo: "좋은 아침입니다. 오늘도 잘 부탁드립니다." },
      { speaker: "staff", japanese: "おはようございます。", reading: "おはようございます。", meaningKo: "좋은 아침입니다." },
    ],
    prompts: [
      { id: "p1", situation: "아침 인사", instructionKo: "출근해서 아침 인사를 해 보세요.", targetAnswer: "おはようございます。", targetReading: "おはようございます。", hints: ["おはようございます"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "부탁 인사", instructionKo: "오늘도 잘 부탁드린다고 말해 보세요.", targetAnswer: "今日もよろしくお願いします。", targetReading: "きょうもよろしくおねがいします。", hints: ["よろしくお願いします"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "업무 중 인사", instructionKo: "수고하신다고 인사해 보세요.", targetAnswer: "お疲れさまです。", targetReading: "おつかれさまです。", hints: ["お疲れさまです"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "workplace-meeting",
    title: "Speak in a Simple Meeting",
    category: "workplace basics",
    difficulty: "lower-intermediate",
    lessonGoal: "Say you understand and ask one follow-up question.",
    explanationKo: "회의에서 아주 짧게 반응하는 문장을 연습합니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "わかりました", reading: "わかりました", meaningKo: "알겠습니다", notesKo: "이해 표현" },
      { id: "e2", japanese: "もう一度お願いします", reading: "もういちどおねがいします", meaningKo: "한 번 더 부탁드립니다", notesKo: "재확인" },
      { id: "e3", japanese: "締め切りはいつですか", reading: "しめきりはいつですか", meaningKo: "마감은 언제인가요?", notesKo: "기한 질문" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "この資料を明日までにお願いします。", reading: "このしりょうをあしたまでにおねがいします。", meaningKo: "이 자료를 내일까지 부탁합니다." },
      { speaker: "learner", japanese: "わかりました。締め切りはいつですか。", reading: "わかりました。しめきりはいつですか。", meaningKo: "알겠습니다. 마감은 언제인가요?" },
    ],
    prompts: [
      { id: "p1", situation: "이해했다 말하기", instructionKo: "알겠다고 답해 보세요.", targetAnswer: "わかりました。", targetReading: "わかりました。", hints: ["わかりました"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "한 번 더 요청", instructionKo: "한 번 더 말해 달라고 해 보세요.", targetAnswer: "もう一度お願いします。", targetReading: "もういちどおねがいします。", hints: ["もう一度"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "마감 질문", instructionKo: "마감이 언제인지 물어보세요.", targetAnswer: "締め切りはいつですか。", targetReading: "しめきりはいつですか。", hints: ["締め切り"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "small-talk-weather",
    title: "Talk About the Weather",
    category: "daily small talk",
    difficulty: "complete-beginner",
    lessonGoal: "Make one small-talk comment about the weather.",
    explanationKo: "대화를 시작하기 좋은 날씨 표현입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "今日は寒いですね", reading: "きょうはさむいですね", meaningKo: "오늘 춥네요", notesKo: "날씨 공감" },
      { id: "e2", japanese: "雨が降りそうです", reading: "あめがふりそうです", meaningKo: "비가 올 것 같아요", notesKo: "예상 표현" },
      { id: "e3", japanese: "傘を持っていますか", reading: "かさをもっていますか", meaningKo: "우산 가지고 있어요?", notesKo: "대화 확장" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "今日は寒いですね。", reading: "きょうはさむいですね。", meaningKo: "오늘 춥네요." },
      { speaker: "staff", japanese: "そうですね。", reading: "そうですね。", meaningKo: "그러네요." },
    ],
    prompts: [
      { id: "p1", situation: "추운 날씨 말하기", instructionKo: "오늘 춥다고 말해 보세요.", targetAnswer: "今日は寒いですね。", targetReading: "きょうはさむいですね。", hints: ["寒いですね"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "비 올 것 같음", instructionKo: "비가 올 것 같다고 말해 보세요.", targetAnswer: "雨が降りそうです。", targetReading: "あめがふりそうです。", hints: ["降りそうです"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "우산 물어보기", instructionKo: "우산이 있는지 물어보세요.", targetAnswer: "傘を持っていますか。", targetReading: "かさをもっていますか。", hints: ["傘"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "small-talk-weekend",
    title: "Talk About Weekend Plans",
    category: "daily small talk",
    difficulty: "beginner",
    lessonGoal: "Say one plan for the weekend.",
    explanationKo: "가벼운 잡담으로 주말 계획을 말하는 연습입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "週末は友だちに会います", reading: "しゅうまつはともだちにあいます", meaningKo: "주말에 친구를 만나요", notesKo: "계획 소개" },
      { id: "e2", japanese: "家でゆっくりします", reading: "いえでゆっくりします", meaningKo: "집에서 푹 쉴 거예요", notesKo: "휴식 표현" },
      { id: "e3", japanese: "あなたはどうですか", reading: "あなたはどうですか", meaningKo: "당신은 어때요?", notesKo: "대화 확장" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "週末は友だちに会います。あなたはどうですか。", reading: "しゅうまつはともだちにあいます。あなたはどうですか。", meaningKo: "주말에 친구를 만나요. 당신은 어때요?" },
      { speaker: "staff", japanese: "家でゆっくりします。", reading: "いえでゆっくりします。", meaningKo: "집에서 쉴 거예요." },
    ],
    prompts: [
      { id: "p1", situation: "주말 계획 말하기", instructionKo: "주말에 친구를 만난다고 말해 보세요.", targetAnswer: "週末は友だちに会います。", targetReading: "しゅうまつはともだちにあいます。", hints: ["友だちに会います"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "집에서 쉬기", instructionKo: "집에서 푹 쉰다고 말해 보세요.", targetAnswer: "家でゆっくりします。", targetReading: "いえでゆっくりします。", hints: ["ゆっくりします"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "상대에게 되묻기", instructionKo: "상대는 어떤지 되물어 보세요.", targetAnswer: "あなたはどうですか。", targetReading: "あなたはどうですか。", hints: ["どうですか"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "daily-greeting-neighbor",
    title: "Talk to a Neighbor",
    category: "daily small talk",
    difficulty: "beginner",
    lessonGoal: "Greet a neighbor and make one friendly comment.",
    explanationKo: "아파트나 숙소에서 부담 없이 말 거는 연습입니다.",
    estimatedMinutes: 4,
    expressions: [
      { id: "e1", japanese: "こんにちは", reading: "こんにちは", meaningKo: "안녕하세요", notesKo: "기본 인사" },
      { id: "e2", japanese: "いつもありがとうございます", reading: "いつもありがとうございます", meaningKo: "항상 감사합니다", notesKo: "정중한 감사" },
      { id: "e3", japanese: "今日はいい天気ですね", reading: "きょうはいいてんきですね", meaningKo: "오늘 날씨 좋네요", notesKo: "가벼운 화제" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "こんにちは。今日はいい天気ですね。", reading: "こんにちは。きょうはいいてんきですね。", meaningKo: "안녕하세요. 오늘 날씨 좋네요." },
      { speaker: "staff", japanese: "そうですね。", reading: "そうですね。", meaningKo: "그러네요." },
    ],
    prompts: [
      { id: "p1", situation: "기본 인사", instructionKo: "이웃에게 안녕하세요라고 말해 보세요.", targetAnswer: "こんにちは。", targetReading: "こんにちは。", hints: ["こんにちは"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "감사 인사", instructionKo: "항상 감사하다고 말해 보세요.", targetAnswer: "いつもありがとうございます。", targetReading: "いつもありがとうございます。", hints: ["ありがとうございます"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "날씨 이야기", instructionKo: "오늘 날씨가 좋다고 말해 보세요.", targetAnswer: "今日はいい天気ですね。", targetReading: "きょうはいいてんきですね。", hints: ["いい天気ですね"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "travel-airport",
    title: "At the Airport Counter",
    category: "travel",
    difficulty: "lower-intermediate",
    lessonGoal: "Ask about baggage and boarding time.",
    explanationKo: "공항 체크인 카운터에서 필요한 기본 표현입니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "荷物を預けたいです", reading: "にもつをあずけたいです", meaningKo: "짐을 부치고 싶어요", notesKo: "수하물 요청" },
      { id: "e2", japanese: "搭乗は何時ですか", reading: "とうじょうはなんじですか", meaningKo: "탑승은 몇 시예요?", notesKo: "시간 질문" },
      { id: "e3", japanese: "ゲートはどこですか", reading: "ゲートはどこですか", meaningKo: "게이트는 어디예요?", notesKo: "위치 질문" },
    ],
    miniDialogue: [
      { speaker: "learner", japanese: "荷物を預けたいです。搭乗は何時ですか。", reading: "にもつをあずけたいです。とうじょうはなんじですか。", meaningKo: "짐을 부치고 싶어요. 탑승은 몇 시예요?" },
      { speaker: "staff", japanese: "三時です。", reading: "さんじです。", meaningKo: "3시입니다." },
    ],
    prompts: [
      { id: "p1", situation: "짐 부치기", instructionKo: "짐을 부치고 싶다고 말해 보세요.", targetAnswer: "荷物を預けたいです。", targetReading: "にもつをあずけたいです。", hints: ["預けたいです"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "탑승 시간", instructionKo: "탑승 시간이 몇 시인지 물어보세요.", targetAnswer: "搭乗は何時ですか。", targetReading: "とうじょうはなんじですか。", hints: ["搭乗"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "게이트 위치", instructionKo: "게이트가 어디인지 물어보세요.", targetAnswer: "ゲートはどこですか。", targetReading: "ゲートはどこですか。", hints: ["ゲート"], keyExpressionIds: ["e3"] },
    ],
  },
  {
    id: "jlpt-speaking-support",
    title: "Explain Your Reason Briefly",
    category: "JLPT support",
    difficulty: "lower-intermediate",
    lessonGoal: "Give a simple reason using から.",
    explanationKo: "시험형 말하기 대비용으로 이유를 덧붙이는 연습입니다.",
    estimatedMinutes: 5,
    expressions: [
      { id: "e1", japanese: "日本語が好きです", reading: "にほんごがすきです", meaningKo: "일본어를 좋아해요", notesKo: "의견 표현" },
      { id: "e2", japanese: "旅行で使いたいからです", reading: "りょこうでつかいたいからです", meaningKo: "여행에서 쓰고 싶어서예요", notesKo: "이유 말하기" },
      { id: "e3", japanese: "毎日練習しています", reading: "まいにちれんしゅうしています", meaningKo: "매일 연습하고 있어요", notesKo: "학습 습관" },
    ],
    miniDialogue: [
      { speaker: "staff", japanese: "どうして日本語を勉強していますか。", reading: "どうしてにほんごをべんきょうしていますか。", meaningKo: "왜 일본어를 공부하나요?" },
      { speaker: "learner", japanese: "旅行で使いたいからです。", reading: "りょこうでつかいたいからです。", meaningKo: "여행에서 쓰고 싶어서예요." },
    ],
    prompts: [
      { id: "p1", situation: "일본어를 좋아함", instructionKo: "일본어를 좋아한다고 말해 보세요.", targetAnswer: "日本語が好きです。", targetReading: "にほんごがすきです。", hints: ["好きです"], keyExpressionIds: ["e1"] },
      { id: "p2", situation: "이유 말하기", instructionKo: "여행에서 쓰고 싶어서라고 말해 보세요.", targetAnswer: "旅行で使いたいからです。", targetReading: "りょこうでつかいたいからです。", hints: ["からです"], keyExpressionIds: ["e2"] },
      { id: "p3", situation: "매일 연습함", instructionKo: "매일 연습한다고 말해 보세요.", targetAnswer: "毎日練習しています。", targetReading: "まいにちれんしゅうしています。", hints: ["毎日"], keyExpressionIds: ["e3"] },
    ],
  },
];
