import type { StudySentence, VocabularyWord } from "@/lib/types";

export const coreVocabularyWords: VocabularyWord[] = [
  { id: "w001", japanese: "私", reading: "わたし", meaningKo: "나, 저", noteKo: "자기소개에서 가장 많이 쓰는 1인칭입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w002", japanese: "あなた", reading: "あなた", meaningKo: "당신", noteKo: "친한 사이보다 교재 문장이나 안내 표현에서 자주 보입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w003", japanese: "人", reading: "ひと", meaningKo: "사람", noteKo: "사람을 뜻하는 기본 명사입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w004", japanese: "名前", reading: "なまえ", meaningKo: "이름", noteKo: "자기소개와 서류 작성에서 자주 씁니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w005", japanese: "日本", reading: "にほん", meaningKo: "일본", noteKo: "나라 이름 기본 표현입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w006", japanese: "韓国", reading: "かんこく", meaningKo: "한국", noteKo: "출신 국가를 말할 때 유용합니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w007", japanese: "学生", reading: "がくせい", meaningKo: "학생", noteKo: "직업과 신분을 말할 때 자주 나옵니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w008", japanese: "先生", reading: "せんせい", meaningKo: "선생님", noteKo: "호칭으로도 자주 쓰입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w009", japanese: "友だち", reading: "ともだち", meaningKo: "친구", noteKo: "일상 대화에서 자주 씁니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w010", japanese: "家族", reading: "かぞく", meaningKo: "가족", noteKo: "자기소개와 일상 대화에서 기본입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },

  { id: "w011", japanese: "今日", reading: "きょう", meaningKo: "오늘", noteKo: "날짜 표현의 출발점입니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w012", japanese: "明日", reading: "あした", meaningKo: "내일", noteKo: "계획을 말할 때 꼭 필요합니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w013", japanese: "昨日", reading: "きのう", meaningKo: "어제", noteKo: "과거 경험을 말할 때 씁니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w014", japanese: "朝", reading: "あさ", meaningKo: "아침", noteKo: "하루 시간대 표현입니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w015", japanese: "昼", reading: "ひる", meaningKo: "낮, 점심때", noteKo: "점심과 연결해 외우기 좋습니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w016", japanese: "夜", reading: "よる", meaningKo: "밤", noteKo: "저녁 이후 시간을 가리킵니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w017", japanese: "今", reading: "いま", meaningKo: "지금", noteKo: "현재 상황을 말할 때 가장 자주 씁니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w018", japanese: "時", reading: "じ", meaningKo: "시", noteKo: "시간 읽기 기본 단위입니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w019", japanese: "分", reading: "ふん", meaningKo: "분", noteKo: "시간과 소요 시간을 말할 때 씁니다.", category: "시간", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w020", japanese: "毎日", reading: "まいにち", meaningKo: "매일", noteKo: "습관을 말할 때 자주 씁니다.", category: "시간", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w021", japanese: "駅", reading: "えき", meaningKo: "역", noteKo: "여행과 길 묻기에서 필수입니다.", category: "장소", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w022", japanese: "学校", reading: "がっこう", meaningKo: "학교", noteKo: "자기소개와 일상에서 자주 나옵니다.", category: "장소", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w023", japanese: "会社", reading: "かいしゃ", meaningKo: "회사", noteKo: "직장 관련 기본 명사입니다.", category: "장소", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w024", japanese: "家", reading: "いえ", meaningKo: "집", noteKo: "사는 곳과 생활 패턴을 말할 때 씁니다.", category: "장소", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w025", japanese: "部屋", reading: "へや", meaningKo: "방", noteKo: "호텔, 집, 기숙사에서 자주 봅니다.", category: "장소", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w026", japanese: "店", reading: "みせ", meaningKo: "가게", noteKo: "쇼핑과 주문 상황에서 자주 씁니다.", category: "장소", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w027", japanese: "病院", reading: "びょういん", meaningKo: "병원", noteKo: "생활 필수 명사입니다.", category: "장소", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w028", japanese: "ホテル", reading: "ホテル", meaningKo: "호텔", noteKo: "여행 상황에서 자주 보입니다.", category: "장소", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w029", japanese: "銀行", reading: "ぎんこう", meaningKo: "은행", noteKo: "생활 인프라 표현입니다.", category: "장소", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w030", japanese: "近く", reading: "ちかく", meaningKo: "근처", noteKo: "위치 질문과 답변에 자주 씁니다.", category: "장소", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w031", japanese: "水", reading: "みず", meaningKo: "물", noteKo: "식당과 생활에서 자주 씁니다.", category: "음식", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w032", japanese: "お茶", reading: "おちゃ", meaningKo: "차", noteKo: "주문과 선택 표현에서 기본입니다.", category: "음식", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w033", japanese: "ご飯", reading: "ごはん", meaningKo: "밥, 식사", noteKo: "먹는 행위와 함께 자주 나옵니다.", category: "음식", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w034", japanese: "パン", reading: "パン", meaningKo: "빵", noteKo: "카페와 아침 식사 표현에 자주 나옵니다.", category: "음식", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w035", japanese: "コーヒー", reading: "コーヒー", meaningKo: "커피", noteKo: "카페 주문의 기본 단어입니다.", category: "음식", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w036", japanese: "牛乳", reading: "ぎゅうにゅう", meaningKo: "우유", noteKo: "편의점과 식생활 표현에서 유용합니다.", category: "음식", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w037", japanese: "肉", reading: "にく", meaningKo: "고기", noteKo: "식당 메뉴를 볼 때 자주 나옵니다.", category: "음식", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w038", japanese: "魚", reading: "さかな", meaningKo: "생선", noteKo: "메뉴 고를 때 자주 보입니다.", category: "음식", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w039", japanese: "果物", reading: "くだもの", meaningKo: "과일", noteKo: "쇼핑과 식생활 표현에서 씁니다.", category: "음식", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w040", japanese: "野菜", reading: "やさい", meaningKo: "채소", noteKo: "음식 취향을 말할 때 유용합니다.", category: "음식", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w041", japanese: "電車", reading: "でんしゃ", meaningKo: "전철", noteKo: "도시 이동에서 가장 많이 쓰는 교통 단어입니다.", category: "교통", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w042", japanese: "バス", reading: "バス", meaningKo: "버스", noteKo: "길 찾기와 이동에서 기본입니다.", category: "교통", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w043", japanese: "タクシー", reading: "タクシー", meaningKo: "택시", noteKo: "여행 상황에서 자주 씁니다.", category: "교통", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w044", japanese: "自転車", reading: "じてんしゃ", meaningKo: "자전거", noteKo: "생활 표현에서 자주 나옵니다.", category: "교통", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w045", japanese: "切符", reading: "きっぷ", meaningKo: "표, 승차권", noteKo: "역에서 꼭 보게 되는 단어입니다.", category: "교통", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w046", japanese: "道", reading: "みち", meaningKo: "길", noteKo: "길 묻기 기본 명사입니다.", category: "교통", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w047", japanese: "右", reading: "みぎ", meaningKo: "오른쪽", noteKo: "방향 표현 기본입니다.", category: "교통", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w048", japanese: "左", reading: "ひだり", meaningKo: "왼쪽", noteKo: "길 안내를 들을 때 자주 나옵니다.", category: "교통", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w049", japanese: "まっすぐ", reading: "まっすぐ", meaningKo: "곧장, 똑바로", noteKo: "길 설명에서 가장 자주 들립니다.", category: "교통", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w050", japanese: "出口", reading: "でぐち", meaningKo: "출구", noteKo: "역과 건물에서 자주 보입니다.", category: "교통", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w051", japanese: "服", reading: "ふく", meaningKo: "옷", noteKo: "쇼핑 기본 명사입니다.", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w052", japanese: "靴", reading: "くつ", meaningKo: "신발", noteKo: "사이즈와 함께 자주 외웁니다.", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w053", japanese: "かばん", reading: "かばん", meaningKo: "가방", noteKo: "쇼핑과 소지품 표현에서 자주 보입니다.", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w054", japanese: "値段", reading: "ねだん", meaningKo: "가격", noteKo: "가격 질문의 핵심 명사입니다.", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w055", japanese: "安い", reading: "やすい", meaningKo: "싸다", noteKo: "가격 감상을 말할 때 씁니다.", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w056", japanese: "高い", reading: "たかい", meaningKo: "비싸다, 높다", noteKo: "가격과 높이 두 뜻이 있습니다.", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w057", japanese: "大きい", reading: "おおきい", meaningKo: "크다", noteKo: "물건 크기를 말할 때 씁니다.", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w058", japanese: "小さい", reading: "ちいさい", meaningKo: "작다", noteKo: "사이즈 요청과 묘사에 자주 씁니다.", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w059", japanese: "新しい", reading: "あたらしい", meaningKo: "새롭다", noteKo: "물건 상태를 말할 때 유용합니다.", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w060", japanese: "古い", reading: "ふるい", meaningKo: "낡다, 오래되다", noteKo: "반대말로 함께 익히기 좋습니다.", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w061", japanese: "行く", reading: "いく", meaningKo: "가다", noteKo: "가장 핵심적인 이동 동사입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w062", japanese: "来る", reading: "くる", meaningKo: "오다", noteKo: "불규칙 활용 기본입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w063", japanese: "帰る", reading: "かえる", meaningKo: "돌아가다", noteKo: "퇴근, 귀가 표현에서 자주 씁니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w064", japanese: "食べる", reading: "たべる", meaningKo: "먹다", noteKo: "1그룹이 아닌 기본 2그룹 동사입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w065", japanese: "飲む", reading: "のむ", meaningKo: "마시다", noteKo: "카페와 식당 표현에서 자주 씁니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w066", japanese: "見る", reading: "みる", meaningKo: "보다", noteKo: "눈으로 보는 행위 기본 동사입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w067", japanese: "聞く", reading: "きく", meaningKo: "듣다, 묻다", noteKo: "문맥에 따라 의미가 달라집니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w068", japanese: "話す", reading: "はなす", meaningKo: "말하다", noteKo: "회화 연습에서 가장 중요한 동사입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w069", japanese: "書く", reading: "かく", meaningKo: "쓰다", noteKo: "문자와 메모에 자주 나옵니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w070", japanese: "読む", reading: "よむ", meaningKo: "읽다", noteKo: "텍스트 학습에서 기본입니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w071", japanese: "買う", reading: "かう", meaningKo: "사다", noteKo: "쇼핑 기본 동사입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w072", japanese: "待つ", reading: "まつ", meaningKo: "기다리다", noteKo: "약속과 교통 상황에서 자주 씁니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w073", japanese: "会う", reading: "あう", meaningKo: "만나다", noteKo: "사람을 만날 때 쓰는 기본 동사입니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w074", japanese: "使う", reading: "つかう", meaningKo: "사용하다", noteKo: "도구와 언어를 말할 때 자주 씁니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w075", japanese: "休む", reading: "やすむ", meaningKo: "쉬다", noteKo: "휴식과 결석 표현에서 자주 씁니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w076", japanese: "勉強する", reading: "べんきょうする", meaningKo: "공부하다", noteKo: "학습자에게 필수인 する 동사입니다.", category: "동사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w077", japanese: "働く", reading: "はたらく", meaningKo: "일하다", noteKo: "직업 소개와 함께 자주 씁니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w078", japanese: "起きる", reading: "おきる", meaningKo: "일어나다", noteKo: "하루 일과 표현의 기본입니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w079", japanese: "寝る", reading: "ねる", meaningKo: "자다", noteKo: "하루 일과와 건강 표현에서 자주 씁니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w080", japanese: "わかる", reading: "わかる", meaningKo: "알다, 이해하다", noteKo: "이해 여부를 말할 때 매우 중요합니다.", category: "동사", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w081", japanese: "いい", reading: "いい", meaningKo: "좋다", noteKo: "구어체에서 よい보다 훨씬 자주 씁니다.", category: "형용사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w082", japanese: "悪い", reading: "わるい", meaningKo: "나쁘다", noteKo: "상태 평가에 자주 씁니다.", category: "형용사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w083", japanese: "暑い", reading: "あつい", meaningKo: "덥다", noteKo: "날씨 표현 기본입니다.", category: "형용사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w084", japanese: "寒い", reading: "さむい", meaningKo: "춥다", noteKo: "스몰토크에서 자주 씁니다.", category: "형용사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w085", japanese: "忙しい", reading: "いそがしい", meaningKo: "바쁘다", noteKo: "일상 상태 설명에 자주 씁니다.", category: "형용사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w086", japanese: "暇", reading: "ひま", meaningKo: "한가함", noteKo: "な형용사처럼 씁니다.", category: "형용사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w087", japanese: "好き", reading: "すき", meaningKo: "좋아함", noteKo: "な형용사처럼 활용합니다.", category: "형용사", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w088", japanese: "嫌い", reading: "きらい", meaningKo: "싫어함", noteKo: "취향 반대 표현입니다.", category: "형용사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w089", japanese: "きれい", reading: "きれい", meaningKo: "예쁘다, 깨끗하다", noteKo: "의미가 두 갈래로 쓰입니다.", category: "형용사", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w090", japanese: "元気", reading: "げんき", meaningKo: "건강함, 활기참", noteKo: "안부 묻기에서 가장 많이 씁니다.", category: "형용사", difficulty: "complete-beginner", jlptLevel: "N5" },

  { id: "w091", japanese: "お金", reading: "おかね", meaningKo: "돈", noteKo: "생활과 쇼핑에서 기본입니다.", category: "생활", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w092", japanese: "時間", reading: "じかん", meaningKo: "시간", noteKo: "약속과 일정에서 자주 씁니다.", category: "생활", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w093", japanese: "電話", reading: "でんわ", meaningKo: "전화", noteKo: "연락 표현에서 자주 나옵니다.", category: "생활", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w094", japanese: "傘", reading: "かさ", meaningKo: "우산", noteKo: "날씨 대화와 연결해 외우기 좋습니다.", category: "생활", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w095", japanese: "天気", reading: "てんき", meaningKo: "날씨", noteKo: "스몰토크 기본 명사입니다.", category: "생활", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w096", japanese: "雨", reading: "あめ", meaningKo: "비", noteKo: "날씨 묘사에 자주 씁니다.", category: "생활", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w097", japanese: "雪", reading: "ゆき", meaningKo: "눈", noteKo: "겨울 날씨 표현에서 자주 나옵니다.", category: "생활", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w098", japanese: "仕事", reading: "しごと", meaningKo: "일, 업무", noteKo: "직장 기초 표현의 기본입니다.", category: "생활", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w099", japanese: "宿題", reading: "しゅくだい", meaningKo: "숙제", noteKo: "학습 표현에서 자주 씁니다.", category: "생활", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w100", japanese: "質問", reading: "しつもん", meaningKo: "질문", noteKo: "수업과 업무에서 모두 유용합니다.", category: "생활", difficulty: "lower-intermediate", jlptLevel: "N5" },

  { id: "w101", japanese: "こちら", reading: "こちら", meaningKo: "이쪽", noteKo: "정중한 지시 표현입니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w102", japanese: "そちら", reading: "そちら", meaningKo: "그쪽", noteKo: "상대 쪽을 가리킬 때 씁니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w103", japanese: "あちら", reading: "あちら", meaningKo: "저쪽", noteKo: "안내 방송과 길 설명에서 자주 나옵니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w104", japanese: "どこ", reading: "どこ", meaningKo: "어디", noteKo: "위치 질문의 핵심입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w105", japanese: "何", reading: "なに", meaningKo: "무엇", noteKo: "문장 맥락에 따라 なん으로도 읽습니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w106", japanese: "だれ", reading: "だれ", meaningKo: "누구", noteKo: "사람을 묻는 기본 의문사입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w107", japanese: "いつ", reading: "いつ", meaningKo: "언제", noteKo: "시간을 묻는 기본 표현입니다.", category: "기본", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w108", japanese: "どう", reading: "どう", meaningKo: "어떻게", noteKo: "방법과 상태를 물을 때 씁니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w109", japanese: "どうして", reading: "どうして", meaningKo: "왜", noteKo: "이유 질문에서 자주 씁니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w110", japanese: "少し", reading: "すこし", meaningKo: "조금", noteKo: "수량과 정도를 모두 표현할 수 있습니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },

  { id: "w111", japanese: "たくさん", reading: "たくさん", meaningKo: "많이", noteKo: "양이 많을 때 자연스럽게 씁니다.", category: "기본", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w112", japanese: "一つ", reading: "ひとつ", meaningKo: "하나", noteKo: "물건 수량 기본 표현입니다.", category: "수량", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w113", japanese: "二つ", reading: "ふたつ", meaningKo: "둘", noteKo: "물건을 셀 때 자주 씁니다.", category: "수량", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w114", japanese: "三つ", reading: "みっつ", meaningKo: "셋", noteKo: "수량 표현의 기본 묶음입니다.", category: "수량", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w115", japanese: "一人", reading: "ひとり", meaningKo: "한 명", noteKo: "식당과 예약에서 자주 나옵니다.", category: "수량", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w116", japanese: "二人", reading: "ふたり", meaningKo: "두 명", noteKo: "불규칙 읽기라 꼭 익혀야 합니다.", category: "수량", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "w117", japanese: "半", reading: "はん", meaningKo: "반", noteKo: "시간 읽기와 함께 자주 씁니다.", category: "수량", difficulty: "beginner", jlptLevel: "N5" },
  { id: "w118", japanese: "先週", reading: "せんしゅう", meaningKo: "지난주", noteKo: "과거 경험을 말할 때 유용합니다.", category: "시간", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "w119", japanese: "来週", reading: "らいしゅう", meaningKo: "다음 주", noteKo: "일정과 약속에서 자주 나옵니다.", category: "시간", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "w120", japanese: "今週", reading: "こんしゅう", meaningKo: "이번 주", noteKo: "계획 공유에 유용합니다.", category: "시간", difficulty: "lower-intermediate", jlptLevel: "N5" },
];

export const coreStudySentences: StudySentence[] = [
  { id: "s001", japanese: "はじめまして。ミナです。", reading: "はじめまして。みなです。", meaningKo: "처음 뵙겠습니다. 미나입니다.", patternKo: "기본 자기소개", category: "자기소개", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s002", japanese: "韓国から来ました。", reading: "かんこくからきました。", meaningKo: "한국에서 왔어요.", patternKo: "출신지 말하기", category: "자기소개", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s003", japanese: "会社員です。", reading: "かいしゃいんです。", meaningKo: "회사원입니다.", patternKo: "직업 말하기", category: "자기소개", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s004", japanese: "日本語を勉強しています。", reading: "にほんごをべんきょうしています。", meaningKo: "일본어를 공부하고 있어요.", patternKo: "현재 하고 있는 일", category: "자기소개", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s005", japanese: "どうぞよろしくお願いします。", reading: "どうぞよろしくおねがいします。", meaningKo: "잘 부탁드립니다.", patternKo: "정중한 마무리 인사", category: "자기소개", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s006", japanese: "ソウルに住んでいます。", reading: "ソウルにすんでいます。", meaningKo: "서울에 살고 있어요.", patternKo: "사는 곳 말하기", category: "자기소개", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s007", japanese: "二十五歳です。", reading: "にじゅうごさいです。", meaningKo: "스물다섯 살입니다.", patternKo: "나이 말하기", category: "자기소개", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s008", japanese: "趣味は映画を見ることです。", reading: "しゅみはえいがをみることです。", meaningKo: "취미는 영화를 보는 것입니다.", patternKo: "취미 소개하기", category: "자기소개", difficulty: "lower-intermediate", jlptLevel: "N5" },

  { id: "s009", japanese: "コーヒーを一つお願いします。", reading: "コーヒーをひとつおねがいします。", meaningKo: "커피 하나 주세요.", patternKo: "주문 기본형", category: "카페", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s010", japanese: "店内で飲みます。", reading: "てんないでのみます。", meaningKo: "매장에서 마실게요.", patternKo: "매장 이용 말하기", category: "카페", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s011", japanese: "持ち帰りでお願いします。", reading: "もちかえりでおねがいします。", meaningKo: "포장으로 부탁합니다.", patternKo: "포장 요청", category: "카페", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s012", japanese: "氷は少なめでお願いします。", reading: "こおりはすくなめでおねがいします。", meaningKo: "얼음은 적게 부탁해요.", patternKo: "옵션 조절", category: "카페", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s013", japanese: "甘くないほうがいいです。", reading: "あまくないほうがいいです。", meaningKo: "달지 않은 쪽이 좋아요.", patternKo: "선호 말하기", category: "카페", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s014", japanese: "おすすめは何ですか。", reading: "おすすめはなんですか。", meaningKo: "추천은 뭐예요?", patternKo: "추천 묻기", category: "카페", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s015", japanese: "お水もください。", reading: "おみずもください。", meaningKo: "물도 주세요.", patternKo: "추가 요청", category: "카페", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s016", japanese: "ここで写真を撮ってもいいですか。", reading: "ここでしゃしんをとってもいいですか。", meaningKo: "여기서 사진을 찍어도 될까요?", patternKo: "허가 묻기", category: "카페", difficulty: "lower-intermediate", jlptLevel: "N5" },

  { id: "s017", japanese: "袋は大丈夫です。", reading: "ふくろはだいじょうぶです。", meaningKo: "봉투는 괜찮아요.", patternKo: "필요 없음 말하기", category: "편의점", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s018", japanese: "カードで払います。", reading: "カードではらいます。", meaningKo: "카드로 계산할게요.", patternKo: "결제 수단 말하기", category: "편의점", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s019", japanese: "これを温めてください。", reading: "これをあたためてください。", meaningKo: "이걸 데워 주세요.", patternKo: "서비스 요청", category: "편의점", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s020", japanese: "おにぎりはどこですか。", reading: "おにぎりはどこですか。", meaningKo: "삼각김밥은 어디에 있나요?", patternKo: "위치 질문", category: "편의점", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s021", japanese: "この近くにありますか。", reading: "このちかくにありますか。", meaningKo: "이 근처에 있나요?", patternKo: "근처 여부 질문", category: "편의점", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s022", japanese: "一番安いのはどれですか。", reading: "いちばんやすいのはどれですか。", meaningKo: "가장 싼 것은 어느 거예요?", patternKo: "비교 질문", category: "편의점", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s023", japanese: "レシートをください。", reading: "レシートをください。", meaningKo: "영수증 주세요.", patternKo: "영수증 요청", category: "편의점", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s024", japanese: "少し待ってください。", reading: "すこしまってください。", meaningKo: "잠깐 기다려 주세요.", patternKo: "기다려 달라고 말하기", category: "편의점", difficulty: "beginner", jlptLevel: "N5" },

  { id: "s025", japanese: "二人です。", reading: "ふたりです。", meaningKo: "두 명입니다.", patternKo: "인원 말하기", category: "식당", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s026", japanese: "予約していません。", reading: "よやくしていません。", meaningKo: "예약하지 않았어요.", patternKo: "예약 여부 말하기", category: "식당", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s027", japanese: "禁煙席をお願いします。", reading: "きんえんせきをおねがいします。", meaningKo: "금연석 부탁합니다.", patternKo: "자리 요청", category: "식당", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s028", japanese: "このセットをお願いします。", reading: "このセットをおねがいします。", meaningKo: "이 세트를 주세요.", patternKo: "메뉴 주문", category: "식당", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s029", japanese: "飲み物はお茶でお願いします。", reading: "のみものはおちゃでおねがいします。", meaningKo: "음료는 차로 부탁합니다.", patternKo: "선택해서 말하기", category: "식당", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s030", japanese: "辛くない料理がいいです。", reading: "からくないりょうりがいいです。", meaningKo: "맵지 않은 요리가 좋아요.", patternKo: "선호 조건 말하기", category: "식당", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s031", japanese: "おすすめの料理はありますか。", reading: "おすすめのりょうりはありますか。", meaningKo: "추천 요리가 있나요?", patternKo: "추천 요청", category: "식당", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s032", japanese: "お会計をお願いします。", reading: "おかいけいをおねがいします。", meaningKo: "계산 부탁합니다.", patternKo: "계산 요청", category: "식당", difficulty: "beginner", jlptLevel: "N5" },

  { id: "s033", japanese: "駅はどちらですか。", reading: "えきはどちらですか。", meaningKo: "역은 어디 쪽인가요?", patternKo: "방향 질문", category: "길 찾기", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s034", japanese: "歩いて何分ですか。", reading: "あるいてなんぷんですか。", meaningKo: "걸어서 몇 분인가요?", patternKo: "시간 질문", category: "길 찾기", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s035", japanese: "まっすぐ行ってください。", reading: "まっすぐいってください。", meaningKo: "곧장 가 주세요.", patternKo: "길 안내", category: "길 찾기", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s036", japanese: "右に曲がりますか。", reading: "みぎにまがりますか。", meaningKo: "오른쪽으로 도나요?", patternKo: "확인 질문", category: "길 찾기", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s037", japanese: "トイレはどこですか。", reading: "トイレはどこですか。", meaningKo: "화장실은 어디에 있나요?", patternKo: "시설 위치 묻기", category: "길 찾기", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s038", japanese: "この階にありますか。", reading: "このかいにありますか。", meaningKo: "이 층에 있나요?", patternKo: "층 확인", category: "길 찾기", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s039", japanese: "地図を見てもいいですか。", reading: "ちずをみてもいいですか。", meaningKo: "지도를 봐도 될까요?", patternKo: "허가 묻기", category: "길 찾기", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s040", japanese: "ここから遠いですか。", reading: "ここからとおいですか。", meaningKo: "여기서 먼가요?", patternKo: "거리 감각 묻기", category: "길 찾기", difficulty: "lower-intermediate", jlptLevel: "N5" },

  { id: "s041", japanese: "渋谷までいくらですか。", reading: "しぶやまでいくらですか。", meaningKo: "시부야까지 얼마예요?", patternKo: "요금 질문", category: "기차역", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s042", japanese: "切符を一枚ください。", reading: "きっぷをいちまいください。", meaningKo: "표 한 장 주세요.", patternKo: "표 구매", category: "기차역", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s043", japanese: "この電車で大丈夫ですか。", reading: "このでんしゃでだいじょうぶですか。", meaningKo: "이 전철 타면 되나요?", patternKo: "탑승 확인", category: "기차역", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s044", japanese: "新宿で乗り換えます。", reading: "しんじゅくでのりかえます。", meaningKo: "신주쿠에서 갈아탑니다.", patternKo: "환승 말하기", category: "기차역", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s045", japanese: "何番線ですか。", reading: "なんばんせんですか。", meaningKo: "몇 번 승강장이에요?", patternKo: "플랫폼 질문", category: "기차역", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s046", japanese: "急行は止まりますか。", reading: "きゅうこうはとまりますか。", meaningKo: "급행은 서나요?", patternKo: "정차 여부 질문", category: "기차역", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s047", japanese: "出口はあちらです。", reading: "でぐちはあちらです。", meaningKo: "출구는 저쪽입니다.", patternKo: "역 안내", category: "기차역", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s048", japanese: "次の電車はいつですか。", reading: "つぎのでんしゃはいつですか。", meaningKo: "다음 전철은 언제예요?", patternKo: "다음 일정 묻기", category: "기차역", difficulty: "lower-intermediate", jlptLevel: "N5" },

  { id: "s049", japanese: "この服を見てもいいですか。", reading: "このふくをみてもいいですか。", meaningKo: "이 옷을 봐도 될까요?", patternKo: "상품 확인", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s050", japanese: "Mサイズはありますか。", reading: "エムサイズはありますか。", meaningKo: "M 사이즈 있나요?", patternKo: "사이즈 묻기", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s051", japanese: "もう少し大きいのがいいです。", reading: "もうすこしおおきいのがいいです。", meaningKo: "조금 더 큰 게 좋아요.", patternKo: "사이즈 조정", category: "쇼핑", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s052", japanese: "試着してもいいですか。", reading: "しちゃくしてもいいですか。", meaningKo: "입어 봐도 될까요?", patternKo: "허가 요청", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s053", japanese: "これは少し高いです。", reading: "これはすこしたかいです。", meaningKo: "이건 조금 비싸요.", patternKo: "가격 감상", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s054", japanese: "別の色はありますか。", reading: "べつのいろはありますか。", meaningKo: "다른 색은 있나요?", patternKo: "옵션 묻기", category: "쇼핑", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s055", japanese: "これにします。", reading: "これにします。", meaningKo: "이걸로 할게요.", patternKo: "결정 말하기", category: "쇼핑", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s056", japanese: "カードは使えますか。", reading: "カードはつかえますか。", meaningKo: "카드 사용할 수 있나요?", patternKo: "가능 여부 질문", category: "쇼핑", difficulty: "beginner", jlptLevel: "N5" },

  { id: "s057", japanese: "予約しています。", reading: "よやくしています。", meaningKo: "예약했습니다.", patternKo: "체크인 시작", category: "호텔", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s058", japanese: "一泊です。", reading: "いっぱくです。", meaningKo: "1박입니다.", patternKo: "숙박 기간 말하기", category: "호텔", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s059", japanese: "パスポートをお願いします。", reading: "パスポートをおねがいします。", meaningKo: "여권 부탁합니다.", patternKo: "체크인 안내", category: "호텔", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s060", japanese: "タオルをもう一枚ください。", reading: "タオルをもういちまいください。", meaningKo: "수건 한 장 더 주세요.", patternKo: "추가 물품 요청", category: "호텔", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s061", japanese: "Wi-Fiのパスワードは何ですか。", reading: "ワイファイのパスワードはなんですか。", meaningKo: "와이파이 비밀번호는 뭐예요?", patternKo: "정보 요청", category: "호텔", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s062", japanese: "チェックアウトは何時ですか。", reading: "チェックアウトはなんじですか。", meaningKo: "체크아웃은 몇 시예요?", patternKo: "시간 질문", category: "호텔", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s063", japanese: "部屋は静かですか。", reading: "へやはしずかですか。", meaningKo: "방은 조용한가요?", patternKo: "상태 확인", category: "호텔", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s064", japanese: "荷物を預けたいです。", reading: "にもつをあずけたいです。", meaningKo: "짐을 맡기고 싶어요.", patternKo: "희망 표현", category: "호텔", difficulty: "lower-intermediate", jlptLevel: "N5" },

  { id: "s065", japanese: "今日は寒いですね。", reading: "きょうはさむいですね。", meaningKo: "오늘 춥네요.", patternKo: "날씨 스몰토크", category: "일상", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s066", japanese: "雨が降りそうです。", reading: "あめがふりそうです。", meaningKo: "비가 올 것 같아요.", patternKo: "추측 말하기", category: "일상", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s067", japanese: "傘を持っていますか。", reading: "かさをもっていますか。", meaningKo: "우산 가지고 있어요?", patternKo: "소지 여부 묻기", category: "일상", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s068", japanese: "週末は友だちに会います。", reading: "しゅうまつはともだちにあいます。", meaningKo: "주말에 친구를 만나요.", patternKo: "계획 말하기", category: "일상", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s069", japanese: "家でゆっくりします。", reading: "いえでゆっくりします。", meaningKo: "집에서 푹 쉴 거예요.", patternKo: "휴식 계획 말하기", category: "일상", difficulty: "beginner", jlptLevel: "N5" },
  { id: "s070", japanese: "あなたはどうですか。", reading: "あなたはどうですか。", meaningKo: "당신은 어때요?", patternKo: "상대에게 되묻기", category: "일상", difficulty: "complete-beginner", jlptLevel: "N5" },
  { id: "s071", japanese: "今日は少し忙しいです。", reading: "きょうはすこしいそがしいです。", meaningKo: "오늘은 조금 바빠요.", patternKo: "상태 설명", category: "일상", difficulty: "lower-intermediate", jlptLevel: "N5" },
  { id: "s072", japanese: "でも、夜は時間があります。", reading: "でも、よるはじかんがあります。", meaningKo: "하지만 밤에는 시간이 있어요.", patternKo: "반대 연결하기", category: "일상", difficulty: "lower-intermediate", jlptLevel: "N5" },
];
